### ISSUE TITLE
Color picker and date picker not working in Gatsby demo

### ISSUE THREAD

**Issue by andyhu92** [tinacms/tinacms#357]
## Description

When I follow the steps [here](https://tinacms.org/docs/contributing/setting-up) to setup the project, the color picker is not working (the selected color blinked for a sec) and the date picker always select 1 day before my checked date on Gatsby demo page.

### Steps to reproduce

Follow the steps [here](https://tinacms.org/docs/contributing/setting-up) to setup the project -> open sidebar -> click Blog Styles -> Play with color picker or date picker

### Expected result

The background color of header text should be changed when interact with color picker and the date picker should work

### Actual result

The background color of header text only blink for a sec when interact with color picker and the date picker always select the previous date I choose

### Environment

| Tool    | Version     |
| ------- | ----------- |
| tinacms | 96c3f16e9ce9c62ad88b845c7f899bee3c2088cd |
| npm     | 6.4.1     |
| node    | 8.16.1     |

**Comment by jamespohalloran** [comment]
Thanks for the issue! I've seen the color picker issue in the past but am not currently able to reproduce it on master. Did you run the setup commands on the root of the repo to build all packages? https://tinacms.org/docs/contributing/setting-up
If you're just running install from inside the gatsby demo, it might use an older package from npm without the fix.

The date issue should be fixed with this: https://github.com/tinacms/tinacms/pull/326 (which hasn't been published yet, but should be fixed while running the gatsby demo)

**Comment by andyhu92** [comment]
@jamespohalloran I ran the install on the root folder and the color picker issue is still there after remove everything and tried the steps again

**Comment by andyhu92** [comment]
Also when toggle on `Hide Bio`, the navigation section `< Blog Styles` will be hidden

**Comment by kendallstrautman** [comment]
Closing due to inactivity. Please reopen if this continues to be a problem!

**Comment by DirtyF** [comment]
@kendallstrautman I don't have proper rights, but feel free to add https://probot.github.io/apps/stale/ to the repo 😉
