### ISSUE TITLE
Media Manager / Cloudinary integration broken after update to Tina 3.0.x in live mode

### ISSUE THREAD

**Issue by cod3blox** [tinacms/tinacms#6239]
After updating Tina from 2.9.5 to 3.0.2, the Cloudinary Media Store integration in the Media Manager stopped working.

Opening the Media Manager in the Tina UI now results in a "500 – Internal Server Error".

![Image](https://github.com/user-attachments/assets/05936aa4-07f5-479b-8457-1af352a697f1)

The strange thing is that this only happens on the live site (deployed on Netlify). Locally, everything works as expected:

- In local dev mode, the Media Manager works without any issues.
- In a locally built production version (local build + next start), the error also does not occur.
- the issue seems to be related to the serverless environment. 

Below is an excerpt from the Netlify “Function Next.js Server Handler” error logs:

```
Dec 8, 12:45:13 PM: 6ccc8eb3 ERROR  (node:9) Warning: Failed to load the ES module: /var/task/node_modules/next-tinacms-cloudinary/dist/handlers.js. Make sure to set "type": "module" in the nearest package.json file or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)

Dec 8, 12:45:27 PM: 54217a72 ERROR   ⨯ Error: Failed to load external module next-tinacms-cloudinary/dist/handlers.js: SyntaxError: Cannot use import statement outside a module
    at Context.externalRequire [as x] (.next/server/chunks/[turbopack]_runtime.js:514:15)
    at module evaluation (.next/server/chunks/[root-of-the-server]__2f2d85d2._.js:1:26324)
    at instantiateModule (.next/server/chunks/[turbopack]_runtime.js:715:9)
    at getOrInstantiateModuleFromParent (.next/server/chunks/[turbopack]_runtime.js:738:12)
    at Context.esmImport [as i] (.next/server/chunks/[turbopack]_runtime.js:228:20)
    at module evaluation (.next/server/chunks/[root-of-the-server]__2f2d85d2._.js:1:36424)
    at instantiateModule (.next/server/chunks/[turbopack]_runtime.js:715:9)
    at instantiateRuntimeModule (.next/server/chunks/[turbopack]_runtime.js:743:12)
    at getOrInstantiateRuntimeModule (.next/server/chunks/[turbopack]_runtime.js:756:12)
    at Object.m (.next/server/chunks/[turbopack]_runtime.js:765:18)
```

Environment:

- TinaCMS version: 3.0.2 (previously working on 2.9.5)
- Deployment: Netlify (issue only occurs on live site / serverless function)
- Local dev: works correctly, error not reproducible
- Local production build: works correctly, error not reproducible
- It is a Next.js 16 (16.0.7) Site with Cloudinary integrated like in https://tina.io/docs/reference/media/external/cloudinary

Can you please look into this issue?

If this is something I can fix with my Netlify config, please let me know.
Any help, ideas, or guidance on how to fix or work around this issue would be greatly appreciated.

### Reproduction

npx create-tina-app@latest

### System Info

```shell
System:
    OS: Windows 11 10.0.26200
    CPU: (16) x64 AMD Ryzen 9 8945HS w/ Radeon 780M Graphics
    Memory: 11.47 GB / 29.78 GB
  Binaries:
    Node: 22.20.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.9.3 - C:\Program Files\nodejs\npm.CMD
    pnpm: 10.22.0 - C:\Users\kontn\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Chrome: 142.0.7444.176
    Edge: Chromium (140.0.3485.54)
    Firefox: 143.0.4 - C:\Program Files\Mozilla Firefox\firefox.exe
    Firefox Developer Edition: 143.0 - C:\Program Files\Firefox Developer Edition\firefox.exe
  npmPackages:
    @tinacms/auth: ^1.1.0 => 1.1.0
    @tinacms/cli: ^2.0.2 => 2.0.2
    tinacms: ^3.0.2 => 3.0.2
```

### Validations

- [x] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [docs](https://tina.io/docs).
- [x] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by cod3blox** [comment]
Hello, I’m still stuck with all of my installations on Tina 2.10.1. Could someone from the Tina team please look into this and fix the Cloudinary integration—or, more broadly, ensure the esm migration that was done in Tina 3 (see: https://github.com/tinacms/tinacms/pull/5982 and https://github.com/tinacms/tinacms/commit/2e1535dd5495dc390902f2db6ef1f26afb072396 by @brookjeynes-ssw) has been applied consistently across all related Tina modules? I suspect the issues I’m seeing on Netlify are related to that esm migration.

Today I tried upgrading to Tina 3.1.2 again—still no luck. This time, I even downgraded Next.js and React to match the versions used in the official tina-nextjs-starter.

After deploying to Netlify, I’m once again getting an error when opening the Media Manager.

Below is an excerpt from today’s error logs in Netlify (“Function Next.js Server Handler”):
 
```
Dec 19, 02:50:45 PM: 542fa087 ERROR  (node:9) Warning: Failed to load the ES module: /var/task/node_modules/@tinacms/auth/dist/index.js. Make sure to set "type": "module" in the nearest package.json file or use the .mjs extension.Dec 19, 02:50:45 PM: 542fa087 ERROR   ⨯ SyntaxError: Unexpected token 'export'
    at /var/task/node_modules/ (tinacms/auth/dist/index.js:59)
````

![Image](https://github.com/user-attachments/assets/c82a0fa1-fb31-4bc2-8a95-866e6b708fdb)

````
  System:
    OS: Windows 11 10.0.26200
    CPU: (16) x64 AMD Ryzen 9 8945HS w/ Radeon 780M Graphics
    Memory: 8.36 GB / 29.78 GB
  Binaries:
    Node: 22.20.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.9.3 - C:\Program Files\nodejs\npm.CMD
    pnpm: 10.22.0 - C:\Users\kontn\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Chrome: 142.0.7444.176
    Edge: Chromium (140.0.3485.54)
    Firefox: 143.0.4 - C:\Program Files\Mozilla Firefox\firefox.exe
    Firefox Developer Edition: 143.0 - C:\Program Files\Firefox Developer Edition\firefox.exe
  npmPackages:
    @tinacms/auth: ^1.1.1 => 1.1.1 
    @tinacms/cli: ^2.0.5 => 2.0.5 
    tinacms: ^3.1.2 => 3.1.2 
````

**Comment by kulesy** [comment]
Apologies for the wait @cod3blox, looking into this now...

**Comment by kulesy** [comment]
Hey, we have just released a new TinaCMS version 3.1.3 that has the fix!

**Comment by cod3blox** [comment]
Hi, sorry for the delayed reply, I was on Christmas vacation for the last two weeks. 

@kulesy Thanks for taking a look at this.

I tested the patch with Tina v3.2.0, but unfortunately the Media Manager still doesn’t work together with Cloudinary on Netlify. The same issue persists: a 500 Internal Server Error occurs when opening the Media Manager.

I tested the update on two different sites:
- one with Next 15 / React 18
- another with Next 16 / React 19

On the Next 15 / React 18 site I also tried building with Node 20 in addition to Node 22, hoping it might avoid the stricter ESM import issues — but no luck.

Here are the current error messages triggered by next-tinacms-cloudinary package in the server handler:

### Test Site A (Turbopack)

```
Jan 6, 11:14:03 AM: a327bba1 ERROR  (node:9) Warning: Failed to load the ES module: /var/task/node_modules/next-tinacms-cloudinary/dist/handlers.js. Make sure to set "type": "module" in the nearest package.json file or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)Jan 6, 11:14:53 AM: 5f4df977 ERROR  ⨯ Error: Failed to load external module next-tinacms-cloudinary-8a6fda433e209b2f/dist/handlers.js: SyntaxError: Cannot use import statement outside a module
    at Context.externalRequire [as x] (.next/server/chunks/[turbopack]_runtime.js:535:15)
    at module evaluation (.next/server/chunks/[root-of-the-server]__914b0d27._.js:1:36709)
    at instantiateModule (.next/server/chunks/[turbopack]_runtime.js:740:9)
    at getOrInstantiateModuleFromParent (.next/server/chunks/[turbopack]_runtime.js:763:12)
    at Context.esmImport [as i] (.next/server/chunks/[turbopack]_runtime.js:228:20)
    at <unknown> (.next/server/chunks/[root-of-the-server]__914b0d27._.js:1:36897)
    at Context.asyncModule [as a] (.next/server/chunks/[turbopack]_runtime.js:455:5)
    at module evaluation (.next/server/chunks/[root-of-the-server]__914b0d27._.js:1:36857)
    at instantiateModule (.next/server/chunks/[turbopack]_runtime.js:740:9)
    at getOrInstantiateModuleFromParent (.next/server/chunks/[turbopack]_runtime.js:763:12)

```

#### System Info 

```
  Binaries:
    Node: 22.20.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.9.3 - C:\Program Files\nodejs\npm.CMD
    pnpm: 10.22.0 - C:\Users\kontn\AppData\Roaming\npm\pnpm.CMD
  npmPackages:
    @tinacms/auth: ^1.1.2 => 1.1.2 
    @tinacms/cli: ^2.0.7 => 2.0.7 
    next: 16.1.1 => 16.1.1 
    next-tinacms-cloudinary: ^19.0.0 => 19.0.0 
    react: 19.2.3 => 19.2.3 
    react-dom: 19.2.3 => 19.2.3 
    tinacms: ^3.2.0 => 3.2.0 
```

### Test Site B (Webpack)

```
Jan 6, 09:52:37 AM: 00f20f1e ERROR   ⨯ SyntaxError: Cannot use import statement outside a module
    at 78529 (.next/server/pages/api/cloudinary/[...media].js:1:48344)
    at c (.next/server/webpack-api-runtime.js:1:127)
```

#### System Info 

```
  Binaries:
    Node: 22.20.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.9.3 - C:\Program Files\nodejs\npm.CMD
    pnpm: 10.22.0 - C:\Users\kontn\AppData\Roaming\npm\pnpm.CMD
  npmPackages:
    @tinacms/auth: ^1.1.2 => 1.1.2 
    @tinacms/cli: ^2.0.7 => 2.0.7 
    next: ^15.3.8 => 15.5.9 
    next-tinacms-cloudinary: ^19.0.0 => 19.0.0 
    react: ^18.3.1 => 18.3.1 
    react-dom: ^18.3.1 => 18.3.1 
    tinacms: ^3.2.0 => 3.2.0 
```

## --- Update ---

For reference, here is my API Route implementation based on the official Tina Docs (https://tina.io/docs/reference/media/external/cloudinary):

// pages/api/cloudinary/[...media].js

``` 
import { isAuthorized } from '@tinacms/auth'
import { createMediaHandler } from 'next-tinacms-cloudinary/dist/handlers'

export const config = { api: { bodyParser: false } }

export default createMediaHandler({
  cloud_name: process.env.CLOUDINARY_CLOUD_NAME,
  api_key: process.env.CLOUDINARY_API_KEY,
  api_secret: process.env.CLOUDINARY_API_SECRET,
  authorized: async (req, _res) => {
    try {
      if (process.env.NODE_ENV == 'development') {
        return true
      }

      const user = await isAuthorized(req)

      return user && user.verified
    } catch (e) {
      console.error(e)
      return false
    }
  },
})
```

I was able to resolve the issue on my side. It came down to the import used in the API route:

```js
import { createMediaHandler } from 'next-tinacms-cloudinary/dist/handlers'
```

The problem is that next-tinacms-cloudinary is packaged as an ES module, but Netlify’s Node.js runtime treats it as CommonJS.

#### The Fix:
Adding next-tinacms-cloudinary to transpilePackages in the Next.js config

// next.config.js

```js
const nextConfig = {
  transpilePackages: ['next-tinacms-cloudinary'],
  // ...
}
```

It might be worth mentioning this in the Tina docs as well, so other users don’t have to spend a long time chasing down the same issue.

It’s also a bit unfortunate that we still have to use Next.js Pages Router API Routes for this, rather than the current App Router route handlers. 

It would be nice if we finally could get support for Route Handlers in media as described in the discussion here:
https://github.com/tinacms/tinacms/issues/3971
